<link rel="stylesheet" type="text/css" href="${ctx}/static/css/bootstrap.css">
<link rel="stylesheet" href="${ctx}/static/css/bootstrap-datepicker.css" type="text/css"/>
<link rel="stylesheet" href="${ctx}/static/css/style.css" type="text/css"/>
<link rel="stylesheet" href="${ctx}/static/css/layout.css" type="text/css"/>

<script language="javascript" src="${ctx}/static/js/jquery1.10.2.min.js"></script>
<script language="javascript" src="${ctx}/static/js/bootstrap.min.js"></script>
<script language="javascript" src="${ctx}/static/js/bootstrap-datepicker.js"></script>
<script language="javascript" src="${ctx}/static/js/frame.js"></script>