<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/static/css/bootstrap.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/static/css/bootstrap-datepicker.css" type="text/css"/>
<link rel="stylesheet" href="${pageContext.request.contextPath}/static/css/style.css" type="text/css"/>

<script language="javascript" src="${pageContext.request.contextPath}/static/js/jquery1.10.2.min.js"></script>
<script language="javascript" src="${pageContext.request.contextPath}/static/js/bootstrap.min.js"></script>
<script language="javascript" src="${pageContext.request.contextPath}/static/js/bootstrap-datepicker.js"></script>